config/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('accounts/', include('allauth.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('contact/', include("contact.urls")),
    path("", include("movies.urls")),
)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path
from .views import MoviesView, MovieDetailView, AddReview, ActorView, FilterMoviesView, JsonFilterMoviesView, \
    AddStarRating, Search

urlpatterns = [
    path('', MoviesView.as_view(), name='movies_list'),
    path('filter/', FilterMoviesView.as_view(), name='filter'),
    path('json-filter/', JsonFilterMoviesView.as_view(), name='json_filter'),
    path("search/", Search.as_view(), name='search'),
    path("add-rating/", AddStarRating.as_view(), name='add_rating'),
    path('<slug:slug>/', MovieDetailView.as_view(), name='movie_detail'),
    path('review/<int:pk>/', AddReview.as_view(), name='add_review'),
    path('actor/<str:slug>/', ActorView.as_view(), name='actor_detail'),
]

movies/models.py
from datetime import date

from django.db import models


# Create your models here.
from django.urls import reverse


class Category(models.Model):
    name = models.CharField('Kategoriya', max_length=150)
    description = models.TextField("Description")
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Kategoriya"
        verbose_name_plural = "Kategoriyalar"


class Actor(models.Model):
    name = models.CharField('Ism', max_length=150)
    age = models.PositiveSmallIntegerField('Yosh', default=0)
    description = models.TextField('Description')
    image = models.ImageField('Rasm', upload_to="actors/")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("actor_detail", kwargs={"slug": self.name})

    class Meta:
        verbose_name = "Aktyor va Rejissiyor"
        verbose_name_plural = "Aktyorlar va Rejissiyorlar"


class Genre(models.Model):
    name = models.CharField('Nomi', max_length=100)
    descriptions = models.TextField('Description')
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Janr"
        verbose_name_plural = "Janrlar"


class Movies(models.Model):
    title = models.CharField('Title', max_length=100)
    tagline = models.CharField('Tagline', max_length=100, default='')
    descriptions = models.TextField('Description')
    poster = models.ImageField('Poster', upload_to="movies/")
    year = models.PositiveSmallIntegerField('Chiqqan yil', default=2019)
    country = models.CharField('Davlat', max_length=30)
    directors = models.ManyToManyField(Actor, verbose_name='rejissor', related_name='film_director')
    actors = models.ManyToManyField(Actor, verbose_name='aktorlar', related_name='film_actor')
    genres = models.ManyToManyField(Genre, verbose_name='janrlar')
    worl_premiere = models.DateField('Dunyoga korsatilgan vaqti', default=date.today)
    budget = models.PositiveIntegerField('Budjet', default=0, help_text="Summani dollarda korsating")
    fees_in_usa = models.PositiveIntegerField('AQSHda tolovlar', default=0, help_text="Summani dollarda korsating")
    fees_in_world = models.PositiveIntegerField('Dunyoda tolovlar', default=0, help_text="Summani dollarda korsating")
    category = models.ForeignKey(Category, verbose_name='Kategoriya', on_delete=models.SET_NULL, null=True)
    url = models.SlugField(max_length=160, unique=True)
    draft = models.BooleanField("Chernovek", default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("movie_detail", kwargs={"slug": self.url})

    def get_review(self):
        return self.reviews_set.filter(parent__isnull=True)

    class Meta:
        verbose_name = "Kino"
        verbose_name_plural = "Kinolar"


class MovieShots(models.Model):
    title = models.CharField('Title', max_length=100)
    descriptions = models.TextField('Description')
    image = models.ImageField('Rasm', upload_to="movie_shots/")
    movie = models.ForeignKey(Movies, verbose_name='Kino', on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Kinodan kadr"
        verbose_name_plural = "Kinodan kadrlar"


class RatingStar(models.Model):
    value = models.SmallIntegerField('Value', default=0)

    def __str__(self):
        return f"{self.value}"

    class Meta:
        verbose_name = "Yulduz reytingi"
        verbose_name_plural = "Yulduzlar reytingi"
        ordering = ["-value"]


class Rating(models.Model):
    ip = models.CharField('IP adress', max_length=15)
    star = models.ForeignKey(RatingStar, on_delete=models.CASCADE, verbose_name='Yulduzcha')
    movie = models.ForeignKey(Movies, on_delete=models.CASCADE, verbose_name='Kino')

    def __str__(self):
        return f"{self.star} - {self.movie}"

    class Meta:
        verbose_name = "Reyting"
        verbose_name_plural = "Reytinglar"


class Reviews(models.Model):
    email = models.EmailField()
    name = models.CharField('Ism', max_length=100)
    text = models.TextField('Xabar', max_length=5000)
    movie = models.ForeignKey(Movies, on_delete=models.CASCADE, verbose_name='Kino')
    parent = models.ForeignKey('self', verbose_name='Otasi', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return f"{self.name} - {self.movie}"

    class Meta:
        verbose_name = "Sharh"
        verbose_name_plural = "Sharhlar"

movies/forms.py
from django import forms
from snowpenguin.django.recaptcha3.fields import ReCaptchaField

from .models import Reviews, RatingStar, Rating


class ReviewForm(forms.ModelForm):
    captcha = ReCaptchaField()

    class Meta:
        model = Reviews
        fields = ['name', 'email', 'text', 'captcha']
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control border"}),
            "email": forms.EmailInput(attrs={"class": "form-control border"}),
            "text": forms.Textarea(attrs={"class": "form-control border"}),
        }


class RatingForm(forms.ModelForm):
    star = forms.ModelChoiceField(
        queryset=RatingStar.objects.all(),
        widget=forms.RadioSelect(),
        empty_label=None
    )

    class Meta:
        model = Rating
        fields = ("star",)

movies/views.py
from django.db.models import Q
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import ListView, DetailView
from .forms import ReviewForm, RatingForm

from movies.models import Movies, Category, Actor, Genre, Rating


class GenreYear:
    def get_genres(self):
        return Genre.objects.all()

    def get_years(self):
        return Movies.objects.filter(draft=False).values("year")


class MoviesView(GenreYear, ListView):
    model = Movies
    queryset = Movies.objects.filter(draft=False)
    template_name = "movies/movies.html"
    paginate_by = 1

    # def get_context_data(self, *args, **kwargs):
    #     context = super().get_context_data(*args, **kwargs)
    #     context["category"] = Category.objects.all()
    #     return context


class MovieDetailView(GenreYear, DetailView):
    model = Movies
    slug_field = "url"
    template_name = "movies/movie_detail.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context["star_form"] = RatingForm()
        context["form"] = ReviewForm()
        return context


class AddReview(View):
    def post(self, request, pk):
        form = ReviewForm(request.POST)
        movie = Movies.objects.get(id=pk)
        if form.is_valid():
            form = form.save(commit=False)
            if request.POST.get("parent", None):
                form.parent_id = int(request.POST.get("parent"))
            form.movie = movie
            form.save()
        return redirect(movie.get_absolute_url())


class ActorView(DetailView):
    model = Actor
    template_name = "movies/actor.html"
    slug_field = "name"


class FilterMoviesView(GenreYear, ListView):
    template_name = "movies/movies.html"
    paginate_by = 2

    def get_queryset(self):
        queryset = Movies.objects.filter(
            Q(year__in=self.request.GET.getlist("year")) |
            Q(genres__in=self.request.GET.getlist("genre"))
        )
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["year"] = ''.join([f"year={x}&" for x in self.request.GET.getlist("year")])
        context["genre"] = ''.join([f"genre={x}&" for x in self.request.GET.getlist("genre")])
        return context


class JsonFilterMoviesView(ListView):
    def get_queryset(self):
        queryset = Movies.objects.filter(
            Q(year__in=self.request.GET.getlist("year")) |
            Q(genres__in=self.request.GET.getlist("genre"))
        ).distinct().values("title", "tagline", "url", "poster")
        return queryset

    def get(self, request, *args, **kwargs):
        queryset = list(self.get_queryset())
        return JsonResponse({"movies": queryset}, safe=False)


class AddStarRating(View):
    """Добавление рейтинга фильму"""

    def get_client_ip(self, request):
        x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[0]
        else:
            ip = request.META.get('REMOTE_ADDR')
        return ip

    def post(self, request):
        form = RatingForm(request.POST)
        if form.is_valid():
            Rating.objects.update_or_create(
                ip=self.get_client_ip(request),
                movie_id=int(request.POST.get("movie")),
                defaults={'star_id': int(request.POST.get("star"))}
            )
            return HttpResponse(status=201)
        else:
            return HttpResponse(status=400)


class Search(ListView):
    """Поиск фильмов"""
    template_name = "movies/movies.html"
    paginate_by = 3

    def get_queryset(self):
        return Movies.objects.filter(title__icontains=self.request.GET.get("q"))

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["q"] = f'q={self.request.GET.get("q")}&'
        return context

templates/movies/actor.html
{% extends 'movies/base.html' %}
{% load static %}
{% block title %}{{ actor.name }}{% endblock %}
{% block container %}
    <div class="container py-md-3">
{% endblock container %}
{% block sidebar %}
    <div class="side-bar col-lg-3">
{% endblock sidebar %}
{% block movie %}
    <div class="left-ads-display col-lg-8">
        <div class="row">
            <div class="desc1-left col-md-6">
                <img src="{{ actor.image.url }}" class="img-fluid" alt="">
            </div>
            <div class="desc1-right col-md-6 pl-lg-4">
                <h3 class="editContent" style="outline: none; cursor: inherit;">{{ actor.name }}</h3>
                <h5 class="editContent">Terminator: Dark Fate</h5>
                <ul>
                    <li><span><b>Age:</b> {{ actor.age }} yosh</span></li>
                    <li>
                        <span><b>Режиссер:</b>
                            {% for movie in actor.film_director.all %}
                                {{ movie.title }}
                            {% endfor %}
                        </span>
                    </li>
                    <li>
                        <span><b>Актер:</b>
                            {% for movie in actor.film_actor.all %}
                                {{ movie.title }}
                            {% endfor %}
                        </span>
                    </li>
                </ul>
            </div>
        </div>
        <div class="row sub-para-w3layouts mt-5">
            <h3 class="shop-sing editContent">О {{ actor.name }}</h3>
            <p class="editContent">{{ actor.description|safe }}.</p>
        </div>
    </div>
{% endblock movie %}

templates/movies/base.html
{% extends 'base.html' %}
{% block title %}{% endblock %}
{% block content %}
    <section class="ab-info-main py-md-5 py-4 editContent"
             style="padding-left: 3rem; padding-right: 3rem;">
        {% block container %}
            <div class="container-fluid py-md-3">
        {% endblock container %}
        <div class="row">
            {% block sidebar %}
                <div class="side-bar col-lg-3">
            {% endblock sidebar %}
            {% include 'include/sidebar.html' %}
            </div>
            {% block movie %}
            {% endblock movie %}
        </div>
        </div>
    </section>
{% endblock content %}

templates/movies/movie_detail.html
{% extends 'movies/base.html' %}
{% load static i18n %}
{% block title %}{{ movies.title }}{% endblock %}
{% block container %}
    <div class="container py-md-3">
{% endblock container %}
{% block sidebar %}
    <div class="side-bar col-lg-3">
{% endblock sidebar %}
{% block movie %}
    <div class="left-ads-display col-lg-8">
        <div class="row">
            <div class="desc1-left col-md-6">
                <img src="{{ movies.poster.url }}" class="img-fluid" alt="">
            </div>
            <div class="desc1-right col-md-6 pl-lg-4">
                <h3 class="editContent" style="outline: none; cursor: inherit;">{{ movies.title }}</h3>
                <h5 class="editContent">Terminator: Dark Fate</h5>
                <ul>
                    <li style="list-style: none"><span><b>{% trans 'Год' %}:</b> {{ movies.year }}</span></li>
                    <li style="list-style: none"><span><b>Страна:</b> {{ movies.country }}</span>
                    </li>
                    <li style="list-style: none"><span><b>Слоган:</b> {{ movies.tagline }}</span>
                    </li>
                    <li style="list-style: none">
                                    <span><b>Режиссер:</b>
                                        {% for director in movies.directors.all %}
                                            <a href="{{ director.get_absolute_url }}">{{ director.name }},</a>
                                        {% endfor %}
                                    </span>
                    </li>
                    <li>
                        <span><b>Актеры:</b>
                            {% for actor in movies.actors.all %}
                                <a href="{{ actor.get_absolute_url }}">{{ actor.name }}</a>,
                            {% endfor %}
                                </span></li>
                    <li style="list-style: none"><span><b>Жанр:</b>
                        {% for genre in movies.genres.all %}
                            {{ genre.name }}
                        {% endfor %}
                                </span>
                    </li>
                    <li style="list-style: none"><span><b>Премьера в мире:</b> {{ movies.worl_premiere }}</span>
                    </li>
                    <li style="list-style: none">
                        <span><b>Бюджет:</b> ${{ movies.budget }}</span></li>
                    <li style="list-style: none">
                        <span><b>Сборы в США:</b> ${{ movies.fees_in_usa }}</span></li>
                    <li style="list-style: none"><span><b>Сборы в мире:</b> ${{ movies.fees_in_world }}</span>
                    </li>
                    <li>
                        <form action="{% url 'add_rating' %}" method="post" name="rating">
                            {% csrf_token %}
                            <b>Рейтинг:</b>
                            <input type="hidden" value="{{ movies.id }}" name="movie">
                            <span class="rating">
                                {% for k, v in star_form.fields.star.choices %}
                                    <input type="radio" id="rating{{ v }}" name="star" value="{{ k }}">
                                    <label for="rating{{ v }}">{{ k }}</label>
                                {% endfor %}

                            </span>
                            <span class="editContent">5.0</span>

                        </form>
                    </li>
                </ul>
                <div class="share-desc">
                    <div class="share">
                        <h4 class="editContent"
                            style="outline: none; cursor: inherit;">
                            Share:</h4>
                        <ul class="w3layouts_social_list list-unstyled">
                            <li>
                                <a href="#" class="w3pvt_facebook editContent"
                                   style="outline: none; cursor: inherit;">
                                                <span class="fa fa-facebook-f"
                                                      style="outline: none; cursor: inherit;"></span>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="w3pvt_twitter editContent"
                                   style="outline: none; cursor: inherit;">
                                                <span class="fa fa-twitter"
                                                      style="outline: none; cursor: inherit;"></span>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="w3pvt_dribble editContent"
                                   style="outline: none; cursor: inherit;">
                                                <span class="fa fa-dribbble"
                                                      style="outline: none; cursor: inherit;"></span>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
        <div class="row sub-para-w3layouts mt-5">
            <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;">
                О Филме {{ movies.title }}</h3>
            <p>
                {% for image in movies.movieshots_set.all %}
                    <img src="{{ image.image.url }}" class="img-movie-shots" alt="{{ image.descriptions }}">
                {% endfor %}
            </p>
            <p class="editContent" style="outline: none; cursor: inherit;">{{ movies.descriptions | safe }}.</p>
        </div>
        <hr>
        <div class="row">
            <div class="single-form-left">
                <!-- contact form grid -->
                <div class="contact-single">
                    <h1 class="editContent" style="outline: none; cursor: inherit;">
                        <span class="sub-tittle editContent">{{ movies.reviews_set.count }}</span>
                        Оставить отзыв</h1>

                    <form action="{% url 'add_review' movies.id %}" method="post" class="mt-4" id="formReview">
                        {% csrf_token %}
                        <input type="hidden" name="parent" id="contactparent" value="">
                        <div class="form-group editContent">
                            <label for="contactcomment" class="editContent">Ваш комментарий *</label>
                            {{ form.text }}
                        </div>
                        <div class="d-sm-flex">
                            <div class="col-sm-6 form-group p-0 editContent">
                                <label for="contactusername" class="editContent">Имя *</label>
                               {{ form.name }}
                            </div>
                            <div class="col-sm-6 form-group ml-sm-3 editContent"
                                 style="outline: none; cursor: inherit;">
                                <label for="contactemail" class="editContent">Email *</label>
                                {{ form.email }}
                            </div>
                            {{ form.captcha }}
                        </div>
                        <button type="submit"
                                class="mt-3 btn btn-success btn-block py-3">Отправить
                        </button>
                    </form>
                </div>
                <!--  //contact form grid ends here -->
            </div>
            {% for review in movies.get_review %}
                <div class="media py-5">
                    <img src="{% static 'images/te2.jpg' %}" class="mr-3 img-fluid" alt="image">
                    <div class="media-body mt-4">
                        <h5 class="mt-0 editContent">{{ review.name }}</h5>
                        <p class="mt-2 editContent">{{ review.text }}</p>
                        <a href="#formReview" onclick="addReview('{{ review.name }}', '{{ review.id }}')">Javob
                            berish</a>
                        {% for rew in review.reviews_set.all %}
                            <div class="media mt-5 editContent">
                                <a class="pr-3" href="#">
                                    <img src="{% static 'images/te1.jpg' %}" class="img-fluid "
                                         alt="image" style="outline: none; cursor: inherit;">
                                </a>
                                <div class="media-body">
                                    <h5 class="mt-0 editContent">{{ rew.name }}</h5>
                                    <p class="mt-2 editContent">{{ rew.text }}</p>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <script>
        function addReview(name, id) {
            document.getElementById("contactparent").value = id;
            document.getElementById("contactcomment").innerText = '' + name + ', ';
        }
    </script>
{% endblock movie %}

templates/movies/movies.html
{% extends 'movies/base.html' %}
{% block header %} bg1 {% endblock %}
{% load static %}
{% block movie %}
    <div class="left-ads-display col-lg-9">
        <div class="row">
            {% for movie in movies_list %}
                <div class="col-md-4 product-men">
                    <div class="product-shoe-info editContent text-center mt-lg-4">
                        <div class="men-thumb-item">
                            <img src="{{ movie.poster.url }}" class="img-fluid" alt="">
                        </div>
                        <div class="item-info-product">
                            <h4 class="">
                                <a href="{{ movie.get_absolute_url }}" class="editContent">
                                    {{ movie.title }}</a>
                            </h4>
                            <div class="product_price">
                                <div class="grid-price">
                                    <span class="money editContent">{{ movie.tagline }}</span>
                                </div>
                            </div>
                            <ul class="stars">
                                <li><a href="#"><span class="fa fa-star" aria-hidden="true"></span></a></li>
                                <li><a href="#"><span class="fa fa-star" aria-hidden="true"></span></a></li>
                                <li><a href="#"><span class="fa fa-star-half-o"
                                                      aria-hidden="true"></span></a></li>
                                <li><a href="#"><span class="fa fa-star-half-o"
                                                      aria-hidden="true"></span></a></li>
                                <li><a href="#"><span class="fa fa-star-o" aria-hidden="true"></span></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="grid-img-right mt-4 text-right">
            {% include 'include/pagination.html' %}
        </div>
    </div>
{% endblock %}